# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8081

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        slf4j:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      # 主库数据源
      master:
        url: jdbc:mysql://113.45.174.98:3306/ems_test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&&useSSL=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
        username: xftest
        password: abc123456
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 30
      maxOpenPreparedStatements: 30
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      poolPreparedStatements: true
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: platform
        login-password: 123456
  # redis 配置
  redis:
    # 地址
    host: 113.45.174.98
    # 端口，默认为6379
    port: 6380
    # 数据库索引
    database: 0
    # 密码
    password: 1m77GuboCwhMUsLf
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  data:
    # mongodb
    mongodb:
      # 指定MongoDB服务地址
      host: 113.45.174.98
      # 指定端口，默认就为27017
      port: 27017
      # 指定使用的数据库(集合)
      database: ems_test
      #用户名
      username: xfzz01
      #密码
      password: abc123456
  rabbitmq:
    host: 113.45.174.98 # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /ems # rabbitmq的虚拟host
    username: platform # rabbitmq的用户名
    password: xf2021 # rabbitmq的密码
    publisher:
      confirms: true #如果对异步消息需要回调必须设置为true

# Minio配置
minio:
  url: http://113.45.174.98:9000
  accessKey: xftest
  secretKey: abc123456
  bucketName: platform-test
  name: https://dev.dcscm.vip/minio

env:
  prefix: https://dev.dcscm.vip

flowable:
  database-schema-update: false
  async-executor-activate: false
